# put your configuration values here

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true
workspace_id = "09820612-4746-4e32-971a-5955b7cbba47"
organization_id = "b2a5b74b-3004-4524-ab98-47175d47c6e7"

[sources.filesystem]
bucket_url = "/Users/I556249/.claude/projects/-Users-I556249-PycharmProjects-llm-zoomcamp-rag"


[workspace.settings]
name = "playground"
